---
collections:
- name: community.general
- name: ansible.posix
- name: containers.podman
- name: freeipa.ansible_freeipa

roles:
- name: "patrickjahns.promtail"
- name: "cloudalchemy.node_exporter"
