- include_role:
    name: patrickjahns.promtail
  vars:
    promtail_system_user: root
    promtail_config_clients:
      - url: "https://loki.apps.k8s.hahl.id.au/loki/api/v1/push"
        external_labels:
          host: "{{ inventory_hostname }}"
    promtail_config_scrape_configs:
      - job_name: system
        static_configs:
        - targets:
            - localhost
          labels:
            job: var_logs
            __path__: "/var/log/{messages,secure,cron,*.log}"
        - targets:
            - localhost
          labels:
            job: var_logs_recursive
            __path__: /var/log/**/*.log
  
- include_role:
    name: cloudalchemy.node_exporter
  vars:
    node_exporter_enabled_collectors:
      - "systemd"
      - "processes"