---
- hosts: dmz-proxy
  vars:
    keepalived_vip: 172.16.17.38
    keepalived_interface: eth0
  handlers:

    # restart keepalived
    - name: restart keepalived
      service:
        name: keepalived
        state: restarted

    # restart dnsmasq
    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted

    # restart squid
    - name: restart squid
      service:
        name: squid
        state: restarted

  tasks:

    - name: install keepalived and squid
      package:
        name:
          - squid
          - keepalived
          - dnsmasq
        state: latest

    - name: deploy dnsmasq configuration
      ansible.builtin.template:
        src: ../templates/dmz-proxy/dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
      notify: restart dnsmasq

    - name: deploy chrony configuration
      ansible.builtin.template:
        src: ../templates/dmz-proxy/chrony.conf.j2
        dest: /etc/chrony.conf

    - name: deploy squid configuration
      ansible.builtin.template:
        src: ../templates/dmz-proxy/squid.conf.j2
        dest: /etc/squid/squid.conf
      notify: restart squid

    - name: deploy keepalived check scripts
      ansible.builtin.template:
        src: ../templates/dmz-proxy/squid-check.j2
        dest: /usr/libexec/keepalived/squid-check
      notify: restart keepalived

    - name: deploy keepalived configuration
      ansible.builtin.template:
        src: ../templates/dmz-proxy/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: restart keepalived
