---
- hosts: dmz-lb
  vars:
    keepalived_vip_lb: 10.120.1.5
    keepalived_vip_squid: 10.120.1.6
  handlers:
    # restart keepalived
    - name: restart keepalived
      service:
        name: keepalived
        enabled: true
        state: restarted

    - name: restart squid
      service:
        name: caddy
        enabled: true
        state: restarted

    - name: restart caddy
      service:
        name: caddy
        enabled: true
        state: restarted

  tasks:

    - include_tasks: "common/fapolicyd.yaml"

    - name: dmz-lb | set hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: dmz-lb | install epel-release
      package:
        name:
          - epel-release
        state: latest

    - name: dmz-lb | install software
      package:
        name:
          - keepalived
          - ansible-core
          - squid
          - caddy
        state: latest

    - name: dmz-lb | allow haproxy connct any
      command: "setsebool -P haproxy_connect_any 1"

    - name: dmz-lb | allow haproxy network connect
      command: "setsebool -P httpd_can_network_connect 1"

    - name: dmz-lb | allow haproxy set file limit
      command: "setsebool -P httpd_setrlimit 1"

    - name: deploy keepalived lb check scripts
      ansible.builtin.template:
        src: ../templates/dmz-lb/lb-check.j2
        dest: /usr/libexec/keepalived/lb-check
        mode: 0775
      notify: restart keepalived

    - name: deploy keepalived squid check scripts
      ansible.builtin.template:
        src: ../templates/dmz-lb/squid-check.j2
        dest: /usr/libexec/keepalived/squid-check
        mode: 0775
      notify: restart keepalived

    - name: deploy keepalived configuration
      ansible.builtin.template:
        src: ../templates/dmz-lb/keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: restart keepalived

    - name: deploy sysctl configuration
      ansible.builtin.template:
        src: ../templates/dmz-lb/10-keepalived.conf.j2
        dest: /etc/sysctl.d/10-keepalived.conf

    - name: dmz-lb | deploy caddy config
      ansible.builtin.template:
        src: ../templates/dmz-lb/Caddyfile.j2
        dest: /etc/caddy/Caddyfile
      notify: restart caddy

    - name: dmz-lb | ensure services started
      service:
        name: "{{item}}"
        state: started
        enabled: true
      with_items:
        - keepalived
        - caddy
        - squid
