---
- hosts: ext-ns-master
  tasks:

    - name: set serial
      shell: "date +%s"
      register: serial

    - name: freeze
      block:
        - shell: "rndc freeze"
          failed_when: false

    - name: deploy templates
      ansible.builtin.template:
        src: "../templates/ext-ns/{{item.src}}"
        dest: "{{item.dst}}"
        owner: root
        group: named
      with_items:
        - { src: 'records.hahl.au.j2', dst: '/var/named/named.hahl.au' }

    - name: thaw
      block:
        - shell: "rndc thaw"
          failed_when: false

    - name: reload
      block:
        - shell: "rndc reload"
          failed_when: false
