---
- hosts: vdi-desktop
  vars:
    admin_group: grp-hahl-admins
  handlers:

  tasks:

    - name: vdi-desktop | install packages
      dnf:
        name:
          - lightdm
          - xrdp
          - '@xfce-desktop'
          - '@xfce-apps'
          - '@xfce-extra-plugins'
          - '@xfce-media'
        state: latest